<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="3" total="4" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-11-03T21:52:55 WIB" name="Suite" finished-at="2023-11-03T21:53:08 WIB" duration-ms="13260">
    <groups>
      <group name="Smoke">
        <method signature="errorValidation.homeErrorValidation()[pri:0, instance:org.Appium.errorValidation@142269f2]" name="homeErrorValidation" class="org.Appium.errorValidation"/>
      </group> <!-- Smoke -->
    </groups>
    <test started-at="2023-11-03T21:52:55 WIB" name="End to End Checkout" finished-at="2023-11-03T21:52:55 WIB" duration-ms="9">
    </test> <!-- End to End Checkout -->
    <test started-at="2023-11-03T21:52:55 WIB" name="End to End Checkout Experiment" finished-at="2023-11-03T21:52:55 WIB" duration-ms="1">
    </test> <!-- End to End Checkout Experiment -->
    <test started-at="2023-11-03T21:52:55 WIB" name="Error Validation" finished-at="2023-11-03T21:53:08 WIB" duration-ms="13020">
      <class name="org.Appium.errorValidation">
        <test-method is-config="true" signature="ConfigureAppium()[pri:0, instance:org.Appium.errorValidation@142269f2]" started-at="2023-11-03T21:52:55 WIB" name="ConfigureAppium" finished-at="2023-11-03T21:53:03 WIB" duration-ms="8412" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ConfigureAppium -->
        <test-method signature="homeErrorValidation()[pri:0, instance:org.Appium.errorValidation@142269f2]" started-at="2023-11-03T21:53:03 WIB" name="homeErrorValidation" finished-at="2023-11-03T21:53:07 WIB" duration-ms="3723" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Please enter your name!] but found [Please enter your name]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Please enter your name!] but found [Please enter your name]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at org.Appium.errorValidation.homeErrorValidation(errorValidation.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- homeErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:org.Appium.errorValidation@142269f2]" started-at="2023-11-03T21:53:08 WIB" name="tearDown" finished-at="2023-11-03T21:53:08 WIB" duration-ms="323" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- org.Appium.errorValidation -->
    </test> <!-- Error Validation -->
  </suite> <!-- Suite -->
</testng-results>
